#include "US_TST.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "driver/rmt_tx.h"
#include "esp_log.h"

/*  This code generates two waveforms from the ESP32-S3:
 *   1) a series ("burst") of PULSE_COUNT_PER_BURST pulses at ~1.8 MHz, optionally
 *      followed by a hold at BURST_HOLD_LEVEL for BURST_HOLD_TICKS
 *   2) a "Hi-Z" signal which gates a driver chip into a high-impedance state
 *      (low during the pulse outputs and the hold, high otherwise)
 *
 *  The two waveforms must be aligned in time precisely. An earlier version drove
 *  the Hi-Z signal from a general purpose timer; that could not hold the required
 *  synchronization against the pulses. Both signals are now generated by two
 *  channels of the RMT peripheral, tied together by the RMT TX *sync manager*.
 *
 *  The sync manager is the hardware feature that makes this exact: once channels
 *  are added to it, a channel's tx_start is held until every channel in the group
 *  has been started, so both channels leave the peripheral on the same clock edge
 *  regardless of the latency between the two rmt_transmit() calls. Requirements:
 *    - TX channels only, all in the same RMT group
 *    - identical clock source and resolution_hz
 *    - all channels rmt_enable()d *before* rmt_new_sync_manager() is called
 *    - rmt_sync_reset() before every new synchronized round, otherwise the second
 *      and later bursts drift apart.
 */

static const char *TAG = "rmt_burst test";

static rmt_channel_handle_t s_burst_chan     = NULL;  /* for the pulses */
static rmt_channel_handle_t s_hiZ_chan       = NULL;  /* for the impedance signal */

/* One copy encoder per channel: the copy encoder is stateful (it tracks its
 * position in the payload), so a single handle cannot be shared by two channels
 * transmitting at the same time. */
static rmt_encoder_handle_t s_burst_encoder  = NULL;
static rmt_encoder_handle_t s_hiZ_encoder    = NULL;

static rmt_sync_manager_handle_t s_sync      = NULL;

/* Optional idle lead-in (HIZ_LEAD_TICKS), the pulses themselves, then the
 * optional post-burst hold (BURST_HOLD_TICKS). */
static rmt_symbol_word_t s_burst_symbols[HIZ_LEAD_SYMBOLS + PULSE_COUNT_MAX +
                                         BURST_HOLD_SYMBOLS];
static size_t            s_burst_symbol_count;

/* Usually one symbol: each duration field is 15 bits, so a symbol spans up to
 * 65534 ticks -- ~18 ms, longer than any burst. A long post-burst hold is the
 * one thing that can push the window past that, hence the run of symbols. */
static rmt_symbol_word_t s_hiZ_symbols[HIZ_LOW_SYMBOLS];
static size_t            s_hiZ_symbol_count;

_Static_assert(PULSE_COUNT_PER_BURST <= PULSE_COUNT_MAX,
               "PULSE_COUNT_PER_BURST exceeds PULSE_COUNT_MAX (grow the arrays)");
_Static_assert(HIZ_LEAD_TICKS == 0 || HIZ_LEAD_TICKS >= 2,
               "HIZ_LEAD_TICKS must be 0 or >= 2 ticks");
_Static_assert(HIZ_TAIL_TICKS == 0 || HIZ_TAIL_TICKS >= 2,
               "HIZ_TAIL_TICKS must be 0 or >= 2 ticks");
_Static_assert(BURST_HOLD_TICKS == 0 || BURST_HOLD_TICKS >= 2,
               "BURST_HOLD_TICKS must be 0 or >= 2 ticks");

/* Both waveforms must fit in channel memory alongside the driver's
 * end-of-transmission marker, otherwise transmitting needs a refill ISR. */
_Static_assert(HIZ_LEAD_SYMBOLS + PULSE_COUNT_MAX + BURST_HOLD_SYMBOLS
                   <= RMT_MEM_BLOCK_SYMBOLS - 1,
               "burst waveform does not fit in one RMT memory block");
_Static_assert(HIZ_LOW_SYMBOLS <= RMT_MEM_BLOCK_SYMBOLS - 1,
               "Hi-Z waveform does not fit in one RMT memory block");

/* -------------------------------------------------------------------- */
/* Waveform tables                                                       */
/* -------------------------------------------------------------------- */

/* Emit `ticks` of steady `level` into `dst`, using as many symbols as the 15-bit
 * duration fields require, and return how many symbols that took. Every half
 * written is non-zero -- a duration of 0 is the RMT end-of-transmission marker,
 * so a stray zero would truncate the waveform. `ticks` must be 0 or >= 2.
 *
 * This is only ever used for steady levels (the lead-in, the post-burst hold,
 * the Hi-Z envelope). The pulses are built directly, one symbol per cycle, so
 * the output frequency does not depend on anything here. */
static size_t emit_level(rmt_symbol_word_t *dst, unsigned level, uint32_t ticks)
{
    size_t n = 0;

    while (ticks > 0) {
        uint32_t chunk = (ticks > RMT_SYMBOL_MAX_TICKS) ? RMT_SYMBOL_MAX_TICKS : ticks;

        /* Never leave a 1-tick remainder: it could not be split into two
         * non-zero halves on the next pass. */
        if (ticks - chunk == 1) {
            chunk--;
        }

        dst[n].level0    = level;
        dst[n].duration0 = chunk - (chunk / 2);
        dst[n].level1    = level;
        dst[n].duration1 = chunk / 2;
        n++;

        ticks -= chunk;
    }

    return n;
}

/* Pulse burst on GPIO_BURST_DRIVE: an optional idle lead-in, then one symbol per
 * full cycle (1 tick high, 1 tick low), then an optional hold at
 * BURST_HOLD_LEVEL. The line returns to 0 via the transmit config's eot_level. */
static void build_burst_symbols(void)
{
    size_t n = 0;

    /* Stay idle while the gate leads. */
    n += emit_level(&s_burst_symbols[n], 0, HIZ_LEAD_TICKS);

    for (int i = 0; i < PULSE_COUNT_PER_BURST; i++) {
        s_burst_symbols[n].level0    = 1;
        s_burst_symbols[n].duration0 = 1;
        s_burst_symbols[n].level1    = 0;
        s_burst_symbols[n].duration1 = 1;
        n++;
    }

    /* Park the line for the programmed hold, if any. */
    n += emit_level(&s_burst_symbols[n], BURST_HOLD_LEVEL, BURST_HOLD_TICKS);

    s_burst_symbol_count = n;
}

/* Hi-Z envelope on GPIO_HIZ_DRIVE: hold the gate in the Low-Z state for exactly
 * HIZ_LOW_TICKS, which spans the lead-in, the burst and the post-burst hold. The
 * line returns to Hi-Z via the transmit config's eot_level. */
static void build_hiZ_symbols(void)
{
    s_hiZ_symbol_count = emit_level(s_hiZ_symbols, STATE_LO_Z, HIZ_LOW_TICKS);
}

/* -------------------------------------------------------------------- */
/* RMT setup: two synchronized TX channels                               */
/* -------------------------------------------------------------------- */
void rmt_burst_init(void)
{
    build_burst_symbols();
    build_hiZ_symbols();

    /* Both channels must share clk_src and resolution_hz to be synchronizable. */
    rmt_tx_channel_config_t tx_chan_config = {
        .clk_src            = RMT_CLK_SRC_DEFAULT,
        .gpio_num           = GPIO_BURST_DRIVE,
        .mem_block_symbols  = RMT_MEM_BLOCK_SYMBOLS,
        .resolution_hz      = RMT_RESOLUTION_HZ,
        .trans_queue_depth  = 1,
        .flags.invert_out   = false,
        .flags.with_dma     = false,
        .flags.init_level   = 0,          /* pulse line idles low */
    };
    ESP_ERROR_CHECK(rmt_new_tx_channel(&tx_chan_config, &s_burst_chan));

    /* Same config, gate pin, and idling high so the driver chip is held in Hi-Z
     * from the moment the channel is created -- before the first transmission. */
    tx_chan_config.gpio_num         = GPIO_HIZ_DRIVE;
    tx_chan_config.flags.init_level = STATE_HI_Z;
    ESP_ERROR_CHECK(rmt_new_tx_channel(&tx_chan_config, &s_hiZ_chan));

    rmt_copy_encoder_config_t copy_encoder_config = {};
    ESP_ERROR_CHECK(rmt_new_copy_encoder(&copy_encoder_config, &s_burst_encoder));
    ESP_ERROR_CHECK(rmt_new_copy_encoder(&copy_encoder_config, &s_hiZ_encoder));

    /* Channels must be enabled before joining the sync manager, otherwise
     * rmt_new_sync_manager() returns ESP_ERR_INVALID_STATE. */
    ESP_ERROR_CHECK(rmt_enable(s_burst_chan));
    ESP_ERROR_CHECK(rmt_enable(s_hiZ_chan));

    const rmt_channel_handle_t sync_channels[] = { s_burst_chan, s_hiZ_chan };
    rmt_sync_manager_config_t sync_config = {
        .tx_channel_array = sync_channels,
        .array_size       = sizeof(sync_channels) / sizeof(sync_channels[0]),
    };
    ESP_ERROR_CHECK(rmt_new_sync_manager(&sync_config, &s_sync));
}

/* -------------------------------------------------------------------- */
/* Main burst loop                                                       */
/* -------------------------------------------------------------------- */
void rmt_burst_task(void *arg)
{
    rmt_transmit_config_t burst_tx_config = {
        .loop_count      = 0,          /* single-shot burst */
        .flags.eot_level = 0,          /* pulse line rests low */
    };

    rmt_transmit_config_t hiZ_tx_config = {
        .loop_count      = 0,
        .flags.eot_level = STATE_HI_Z, /* gate returns to Hi-Z when the burst ends */
    };

    while (1) {
        /* Pull both channels back to the starting line: resets each channel's
         * clock divider and memory read pointer. Without this, bursts after the
         * first lose their alignment. */
        ESP_ERROR_CHECK(rmt_sync_reset(s_sync));

        /* Neither channel actually starts until both have been armed, so the
         * order of these two calls and the gap between them do not matter. */
        ESP_ERROR_CHECK(rmt_transmit(s_hiZ_chan, s_hiZ_encoder,
                                     s_hiZ_symbols,
                                     s_hiZ_symbol_count * sizeof(rmt_symbol_word_t),
                                     &hiZ_tx_config));
        ESP_ERROR_CHECK(rmt_transmit(s_burst_chan, s_burst_encoder,
                                     s_burst_symbols,
                                     s_burst_symbol_count * sizeof(rmt_symbol_word_t),
                                     &burst_tx_config));

        /* Both must be idle before the next rmt_sync_reset(). The burst itself is
         * only a few microseconds, but a long post-burst hold is not, so the
         * fault timeout tracks the waveform length (see BURST_WAIT_TIMEOUT_MS). */
        ESP_ERROR_CHECK(rmt_tx_wait_all_done(s_burst_chan, BURST_WAIT_TIMEOUT_MS));
        ESP_ERROR_CHECK(rmt_tx_wait_all_done(s_hiZ_chan, BURST_WAIT_TIMEOUT_MS));

        vTaskDelay(1);   /* block for exactly 1 OS tick before next burst */
    }
}

void app_main(void)
{
    rmt_burst_init();
    ESP_LOGI(TAG, " rmt burst init completed (%u pulses, %u ticks Hi-Z window, "
                  "hold %u ticks at %u)",
             (unsigned)PULSE_COUNT_PER_BURST, (unsigned)HIZ_LOW_TICKS,
             (unsigned)BURST_HOLD_TICKS, (unsigned)BURST_HOLD_LEVEL);

    xTaskCreate(rmt_burst_task, "rmt_burst_task", 4096, NULL, 5, NULL);
    ESP_LOGI(TAG, " task started");
}
